### ISSUE TITLE
Roadmap to v0.3-alpha

### ISSUE THREAD

**Issue by electricjones** [spider/spider#21]
Spider v0.3 will be the first usable, thought not production ready release.

**Features**:
- A `DriverInterface` Contract and abstract for creating drivers
- A basic, fluent `CommandBuilder` that performs CRUD operations, but does not handle traversals or relationships (those come in 0.4)
- Predictable and versatile response formats.
- Fully documented, both at code-level and in guides at http://spider-ogm.readthedocs.org/

**Will not include**, yet
- Traversal query builder
- Models
- Schema
- Unified Spider

**To be completed**:
- [x] Merge new Driver and Responses PR #20 
- [x] Integrate data-manager, `Base\Collection`, and `Base\Object` throughout the system. See #12
- [x] Add return formatting methods to  `CommandBuilder` `set(), tree(), path(), scalar()`. Default to set.
- [x] Add exceptions from #17 
- [x] Refactor the OrientCommandProcessor See #18 
- [x] Remove the LanguageProcessor Convention that couples them to Drivers
- [x] Complete GremlinCommandProcessor and NeoCommandProcessor
- [x] Refactor tests per #33, #26
- [x] Refactor system to use consistent terms (e.g. properties, not fields) See #15 
- [x] Update and build documentation
- [x] Ensure consistency in style, docblocks, and code.
- [x] Automate the build process, or at least something

**Comment by electricjones** [comment]
A solid draft of documentation is up at http://spider-ogm.readthedocs.org/en/develop, including some internals notes and a rough roadmap.

**Comment by dmill-bz** [comment]
ok Cool!!
I've made changes to the builder (the ones we spoke of) locally, but it's made the test suite fail and while I was going in and correcting the tests I figured I would try and fix some of the spaghetti stub issues we had (because one of them was leading to some of the errors I was having). So it might be a heavier PR than originally expected. I'll try and get that in today (hopefully I find the time).

It then shouldn't be too long before I get a `CypherProcessor` up and running. `GremlinProcessor` is a bit of another issue it might need more thinking. I'll create an issue once I get there.

**Comment by electricjones** [comment]
Sounds great. I'd like to do a pre-release for after CypherProcessor is up. We can leave GremlinProcessor unsupported for now. At least until we work out how the `CommandBag` will hold traversals.

**Comment by electricjones** [comment]
Oh yeah, be sure to pull or look at a few recent commits. I switched the constructor arguments in `Connection` so you can pass a config connection up front. That should be the only change that matters to the rest of the code.

I am done committing to the `develop` branch for a while. I won't have as much time next week, so I'm going to create a branch and start working on the top-level Spider and a way to integrate Events, Caching, and Logging into the loop, even if no implementations.

After that: Traversals in full force.

**Comment by electricjones** [comment]
Added a couple housekeeping tasks

**Comment by dmill-bz** [comment]
ok what's left here? do you want to set up a scrutinizer for style consistency and such?

**Comment by dmill-bz** [comment]
I could configure the account if you can give me rights for it (It would probably be best if you created it since you own the organization)

**Comment by electricjones** [comment]
I am updating docs and scrutinizing now. How do I give you rights? Do you need admin rights? You should have those anyway. The bus factor and all that.

**Comment by electricjones** [comment]
You are now an admin. I don't what other rights to give you. I think coveralls requires you to be public, but I see you made yourself public already.

**Comment by dmill-bz** [comment]
Thanks. I'm trying to figure this one out. Scrutinizer is complaining about something I'll see if I can sort it out

**Comment by electricjones** [comment]
I am scrutinizing for style now. I've also updated the docs. Pushing in a minute.

**Comment by dmill-bz** [comment]
Ok it looks like I don't have administrative rights to the repo for some reason. (only push & pull rights). The admin group must be just shy in terms of rights.

**Comment by electricjones** [comment]
Weird. I have a ticket open with coveralls, but no matter how hard I try, I can't get the repos to sync. I also created another user, spider-ogm, in hopes it would sync, but that was to no avail. Is there another code coverage system you like? I'm not married to coveralls.

**Comment by electricjones** [comment]
We seem to be good here.
